web:
  restart: always
  build: ./
  ports:
    - "8000:8000"
    - "5000:5000"
  volumes:
    - /usr/src/app/static
  links:
    - postgres:postgres
  environment:
    - PYTHONPATH=/usr/src/app/
    - GROWSER_CONFIG=/usr/src/app/growser.cfg
  command: gunicorn -b :8000 growser.web:app

nginx:
  restart: always
  build: ./deploy/nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - web
  links:
    - web:web

data:
  restart: always
  build: ./deploy/postgres/
  volumes:
    - /var/lib/postgresql
    - ./data:/data
  command: "true"

postgres:
  restart: always
  build: ./deploy/postgres/
  volumes_from:
    - data
  ports:
    - "5432:5432"
